### ISSUE TITLE
Test failures during "make check" stage of build

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app-bundler#33]
Some tests are failing or producing error messages during the "make check" stage of the "brew install" that aren't failing when I run them in the installed app.

```
  libinterp/corefcn/graphics.cc-tst ........................... PASS     46/47  
                                                                  FAIL    1
                                                (missing feature) SKIP    3
...
  plot/util/copyobj.m .........................................  ./base/gsicc_manage.c:1172: gsicc_open_search(): Could not find default_rgb.icc 
| ./base/gsicc_manage.c:1838: gsicc_set_device_profile(): cannot find device profile
 PASS      1/2   
                                                                  FAIL    1
...
  plot/util/hgsave.m ..........................................  ./base/gsicc_manage.c:1172: gsicc_open_search(): Could not find default_rgb.icc 
| ./base/gsicc_manage.c:1838: gsicc_set_device_profile(): cannot find device profile
 PASS      3/4   
                                                                  FAIL    1
...

  publish.tst .................................................  ./base/gsicc_manage.c:1172: gsicc_open_search(): Could not find default_rgb.icc 
| ./base/gsicc_manage.c:1838: gsicc_set_device_profile(): cannot find device profile
  ./base/gsicc_manage.c:1172: gsicc_open_search(): Could not find default_rgb.icc 
| ./base/gsicc_manage.c:1838: gsicc_set_device_profile(): cannot find device profile
  ./base/gsicc_manage.c:1172: gsicc_open_search(): Could not find default_rgb.icc 
| ./base/gsicc_manage.c:1838: gsicc_set_device_profile(): cannot find device profile
  ./base/gsicc_manage.c:1172: gsicc_open_search(): Could not find default_rgb.icc 
| ./base/gsicc_manage.c:1838: gsicc_set_device_profile(): cannot find device profile
  ./base/gsicc_manage.c:1172: gsicc_open_search(): Could not find default_rgb.icc 
| ./base/gsicc_manage.c:1838: gsicc_set_device_profile(): cannot find device profile
  ./base/gsicc_manage.c:1172: gsicc_open_search(): Could not find default_rgb.icc 
| ./base/gsicc_manage.c:1838: gsicc_set_device_profile(): cannot find device profile
  ./base/gsicc_manage.c:1172: gsicc_open_search(): Could not find default_rgb.icc 
| ./base/gsicc_manage.c:1838: gsicc_set_device_profile(): cannot find device profile
 PASS      2/2   
...

Summary:

  PASS                            14935
  FAIL                                3
```

[make-check.log](https://github.com/octave-app/octave-app-bundler/files/2131353/make-check.log)

**Comment by schoeps** [comment]
I think this is a consequence of our non-standard ghostscript folder. This is fixed in the installed app by

https://github.com/octave-app/octave-app-bundler/blob/72f868d33399ebba8388d397224a57df30b148ae/bundle_octave#L401

We could export `GS_OPTIONS` in `bundle_octave`

**Comment by apjanke** [comment]
> We could export GS_OPTIONS in bundle_octave

Aha, so that's what GS_OPTIONS was for! You had it in there but I [removed it](https://github.com/octave-app/octave-app-bundler/commit/0938e8a00a7bd50016bd0c53e7ebf4444b7d3e94) because I thought it was a redundancy from constructing the AppleScript. I have restored it, in https://github.com/octave-app/octave-app-bundler/commit/9343a808fa5e542ac92eb165e9cd19d683e14fae, but the test is still failing.

Here's one of the failures.

```
>>>>> processing /private/tmp/octave-octave-app_4.4.0-20180625-41714-f1psuf/octave-4.4.0/scripts/plot/util/copyobj.m
***** testif HAVE_MAGICK; any (strcmp ("gnuplot", available_graphics_toolkits ()))
...
png1 = [tempname() ".png"];
   png2 = [tempname() ".png"];
   unwind_protect
     print (h1, png1);
     [img1, map1, alpha1] = imread (png1);
     print (h2, png2);
     [img2, map2, alpha2] = imread (png2);
   unwind_protect_cleanup
     unlink (png1);
     unlink (png2);
   end_unwind_protect
...
!!!!! test failed
imread: unable to find file '/tmp/oct-u0UDYV.png'
```

Perhaps `brew`'s sandboxing is preventing `octave` from writing to the global `/tmp` directory. I'll see if tempname() can be repointed.

**Comment by apjanke** [comment]
The more I think about this, the more I think this `make check` is actually in the wrong place, and we shouldn't be adding in environment variables and other settings to make it work. Instead, we should either:

a) be moving the check down after we munge & decorate the app, and test the final app and its wrapper script, or
b) be building a wrapper script as part of the Homebrew `octave` formula, and test that

Because we should be testing the final `octave` command as it's presented to the user, and the wrapper script should be taking responsibility for configuring the PATH and GS_OPTIONS and whatnot, and we want to test *that* mechanism. Setting environment variables as part of the test environment is cheating.

**Comment by schoeps** [comment]
Agreed!

**Comment by schoeps** [comment]
The question is how to automize that without a lot of work... the app can open an m-file but it will not execute it. We may need GUI scripting.

**Comment by apjanke** [comment]
I think the `octave --eval CODE` command line option would work here. We could use that to point it at a script for execution, and use a little temporary script that just executes the test suite. For example, `octave --eval "cd /path/to/our/test/script; octave_app_test_script"`. Extend our wrapper script to expose the `--eval` option, and I think this is doable.

**Comment by schoeps** [comment]
We could also add another `on run_octave_test` function to `main.scpt` but I am not sure how to call that from shell. I think `osascript ` always executes `run`.

**Comment by apjanke** [comment]
Perhaps we could introduce a special `--run-test-suite` argument that `main.scpt` respects inside `run`, and have it just do a headless run of the test suite in that case.

**Comment by schoeps** [comment]
Ok! we could do something like this
```
on run_octave_test()
	return "cd ~;clear;/Applications/Octave-4.4.0.app/Contents/Resources/usr/bin/octave --no-window-system --eval '__run_test_suite__' >> ~/octave.txt;exit;"
end run_octave_test

on run argv
	path_check()
	cache_fontconfig()
	if argv contains "--run-test-suite" then
		set cmd to export_gs_options() & export_gnuterm() & export_path() & export_dyld() & run_octave_test()
	else
		set cmd to export_gs_options() & export_gnuterm() & export_path() & export_dyld() & run_octave_gui()
	end if
	set output to do shell script cmd
end run
```
which allows to run `osascript /Applications/Octave-4.4.0.app/Contents/Resources/Scripts/main.scpt '--run-test-suite'` which generates a `~/octave.txt`.

**Comment by apjanke** [comment]
Calling this fixed since we have a repeatable clean test run in our bundled app.
